---
- name: add localhost seed hosts
  hosts: localhost
  add_host:
    hostname: localhost
    groups:
      - seed-hosts
    ansible_connection: local
    ansible_host: localhost

- name: load inventory for client projects
  hosts: localhost
  include_vars:
    dir: vars
    files_matching: seed-hosts.yml

- name: create projects, groups, and users
  hosts: localhost
  import_role:
    name: OPENSHIFT-APPLIER

- name: create all users
  script: addUsers.sh
  when: "'masters' in host_groups"
