---
- name: fetch kube config from masters
  fetch:
    src: /root/.kube/config
    dest: /root/.kube/config
    flat: yes
    tags: check-role
  when: "'masters' in group_names"

- name: check system:admin
  shell: oc whoami
  when: "inventory_hostname == 'localhost'"
  tags: check-role

- name: check nodes
  shell: oc get nodes
  when: "inventory_hostname == 'localhost'"
  tags: check-role

- name: add admin user to htpasswd
  shell: htpasswd -b /etc/origin/master/htpasswd admin r3dh4t1!
  when: "'masters' in group_names"
  tags: add-admin

- name: add cluster admin role to admin user
  shell: oc adm policy add-cluster-role-to-user cluster-admin admin
  when: "inventory_hostname == 'localhost'"
  tags: add-admin
