---
- name: create smoke test script file
  template: src=deployment_smoke_test.sh.j2 dest=/root/deployment_smoke_test.sh
  mode: 0770
  tags: smoke-test

- name: run smoke test
  shell: /root/deployment_smoke_test.sh
  tags: smoke-test
