---
- name: Setup GUID
  hosts: all,localhost
  roles:
    - SETUP_GUID

- name: Prerequisite checks
  hosts: nodes, nfs
  roles:
    - PREREQ_CHECKS

- name: Install Req Packages on bastion
  hosts: localhost
  roles:
    - INSTALL_REQUIREMENTS

- name: Write target inventory file
  hosts: localhost
  roles:
    - CREATE_HOST_FILE

- name: run prerequisites playbook for openshift
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml

- name: run deployer playbook for openshift
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml

- name: run some post deploy tasks
  hosts: all,localhost
  roles:
    - POST_DEPLOY_TASKS

- name: prepare and run smoke test after cluster deploy
  hosts: localhost
  roles:
    - TEST_DEPLOYMENT

- name: create pvs and all depended stuff
  hosts: nfs,localhost
  roles:
    - PV_CREATION

- name: create cicd pipeline
  hosts: localhost
  roles:
    - CICD

- name: create multitenancy
  hosts: masters,localhost
  role:
    - MULTIPLE_CLIENTS
