---
- name: Setup GUID
  hosts: all,localhost
  roles:
    - SETUP_GUID

- name: Prerequisite checks
  hosts: nodes, nfs
  roles:
    - PREREQ_CHECKS

- name: Install Req Packages on bastion
  hosts: localhost
  roles:
    - INSTALL_REQUIREMENTS

- name: Write target inventory file
  hosts: localhost
  role:
    - CREATE_HOST_FILE
