---
- name: Setup GUID
  hosts: all,localhost
  roles:
    - SETUP_GUID

- name: Prerequisite checks
  hosts: nodes, nfs
  roles:
    - PREREQ_CHECKS

- name: Install Req Packages on bastion
  hosts: localhost
  roles:
    - INSTALL_REQUIREMENTS

- name: Write target inventory file
  hosts: localhost
  roles:
    - CREATE_HOST_FILE

- name: run prerequisites playbook for openshift
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml

- name: run deployer playbook for openshift
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml
