---
- name: "Create custom fact directory"
  file:
    path: "/etc/ansible/facts.d"
    recurse: yes
    state: "directory"

- name: "Insert custom fact file"
  copy:
    src: files/guid.fact
    dest: /etc/ansible/facts.d/guid.fact
    mode: 0755

- name: re-read facts
  setup:
    filter: ansible_local

- name: set guid if not done yet 
  lineinfile:
    path: /root/.bash_profile
    regexp: '^export GUID=.*'
    line: "export GUID={{ ansible_local['guid']['guid'] }}"
